runtime: php82
env: standard

handlers:
  # Serve Vite-built static assets
  - url: /build/(.*)
    static_files: public/build/\1
    upload: public/build/.*

  # Serve other static files (e.g., favicon.ico)
  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: public/\1
    upload: public/.*\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$

  # Serve Laravel for all routes (React SPA and API)
  - url: /.*
    script: auto
    secure: always

env_variables:
  APP_NAME: LLNHS
  APP_ENV: local
  APP_KEY: base64:g5WibRGv/5A0OGPPsdq7hdx5yp5Zch2iNuTHnjBfus0=
  APP_DEBUG: false
  APP_TIMEZONE: UTC
  APP_URL: http://localhost:8000

  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US

  APP_MAINTENANCE_DRIVER: file

  PHP_CLI_SERVER_WORKERS: 4

  BCRYPT_ROUNDS: 12

  LOG_CHANNEL: stack
  LOG_STACK=: single
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: llnhsDb
  DB_USERNAME: root
  DB_PASSWORD: secret

  SESSION_DRIVER: database
  SESSION_LIFETIME: 120
  SESSION_ENCRYPT: false
  SESSION_PATH: /
  SESSION_DOMAIN: null

  BROADCAST_CONNECTION: log
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: database

  CACHE_STORE: database
  CACHE_PREFIX:

  MEMCACHED_HOST: 127.0.0.1

  REDIS_CLIENT: phpredis
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

  MAIL_MAILER: log
  MAIL_SCHEME: null
  MAIL_HOST: 127.0.0.1
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: 
  AWS_USE_PATH_STYLE_ENDPOINT: false

  VITE_APP_NAME: "${APP_NAME}"