# runtime: php82
# env: standard

# handlers:
#   - url: /build
#     static_dir: public/build
#   - url: /.*
#     script: auto

# env_variables:
#   APP_NAME: LLNHS
#   APP_ENV: local
#   APP_KEY: base64:g5WibRGv/5A0OGPPsdq7hdx5yp5Zch2iNuTHnjBfus0=
#   APP_DEBUG: false
#   APP_TIMEZONE: UTC
#   APP_URL: http://127.0.0.1:8080

#   APP_LOCALE: en
#   APP_FALLBACK_LOCALE: en
#   APP_FAKER_LOCALE: en_US

#   APP_MAINTENANCE_DRIVER: file

#   PHP_CLI_SERVER_WORKERS: 4

#   BCRYPT_ROUNDS: 12

#   LOG_CHANNEL: stack
#   LOG_STACK: single
#   LOG_DEPRECATIONS_CHANNEL: null
#   LOG_LEVEL: debug

#   DB_CONNECTION: mysql
#   DB_HOST: 35.222.73.190
#   DB_PORT: 3306
#   DB_DATABASE: llnhsDb
#   DB_USERNAME: root
#   DB_PASSWORD: secret

#   SESSION_DRIVER: database
#   SESSION_LIFETIME: 120
#   SESSION_ENCRYPT: false
#   SESSION_PATH: /
#   SESSION_DOMAIN: null

#   BROADCAST_CONNECTION: log
#   FILESYSTEM_DISK: local
#   QUEUE_CONNECTION: database

#   CACHE_STORE: database
#   CACHE_PREFIX:

#   MEMCACHED_HOST: 127.0.0.1

#   VITE_APP_NAME: "${APP_NAME}"